<?php
/**
 * Created by PhpStorm.
 * User: guillaumeprost
 * Date: 06/05/2016
 * Time: 12:07
 */

namespace AppBundle\Form\Type\Animal;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

abstract class AnimalType extends AbstractType
{
      /**
       * @param FormBuilderInterface $builder
       * @param array $options
       */
      public function buildForm(FormBuilderInterface $builder, array $options)
      {
            parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

            $builder
                  ->add('breed1', TextType::class, [
                        'label' => 'Breed 1'
                  ])
                  ->add('breed2', TextType::class, [
                        'label' => 'Breed 2'
                  ])
                  ->add('name', TextType::class, [
                        'label' => 'Name of your animal'
                  ])
                  ->add('description', TextareaType::class);
      }

      /**
       * @param OptionsResolver $resolver
       */
      public function configureOptions(OptionsResolver $resolver)
      {
            $resolver->setDefaults([
                  'date_class' => 'AppBundle\Entity\Animal\Animal'
            ]);
      }
}
